### PR TITLE
Clarify the current state of Python 2 vs. 3 support

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Review by ncarding — APPROVED** [review]

**Comment by cclauss** [comment]
@omz please provide feedback on this PR.

**Comment by cclauss** [comment]
@omz please provide feedback on this PR.

**Comment by omz** [comment]
The current state is that I fully intend to support Python 3 in the app template, but I'm very busy with the actual app at the moment... Sorry, I actually wanted to do this much sooner, but various things got in the way.

**Review by omz — APPROVED** [review]

**Comment by omz** [comment]
Thanks for the clarifications in the readme. To be honest, I didn't realize this was a PR at first (thought it was a bugtracker issue for some reason).

**Pull request merged**
